apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-foundations
  namespace: flagger-exercise
  labels:
    app: gitops-foundations
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: a2f33adf0ed6a49d1b2d71eacebef6fa-1424522492.ap-southeast-2.elb.amazonaws.com
      http:
        paths:
          - backend:
              serviceName: gitops-foundations-service
              servicePort: 80
